#!/bin/sh

#TODO This should probably be a Makefile instead.

DEFAULT_FILE="./arduino_cj125.ino"
DEFAULT_BOARD="arduino:avr:leonardo"
DEFAULT_PORT="/dev/ttyACM0"

file="$DEFAULT_FILE"
board="$DEFAULT_BOARD"
port="--port $DEFAULT_PORT"

while getopts vp:f:b: c
do
	case "$c" in
	p) port="--port $OPTARG" ;;
	v) verbose="--verbose-upload" ;;
	f) file="$OPTARG" ;;
	b) board="$OPTARG" ;;
	esac
done

arduino --board $board --upload $port $verbose $file
